name: Build and package for osx

on:
  push:
    branches: [ "newui" ]
  pull_request:
    branches: [ "newui" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build sqlite3
      run: |
        wget https://www.sqlite.org/2023/sqlite-amalgamation-3430100.zip
        7z x sqlite-amalgamation-3430100.zip
        mkdir lib
        clang -shared -fPIC sqlite-amalgamation-3430100/sqlite3.c -o lib/libsqlite3.dylib

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -DVIDEO_EXPORT=0

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Install
      working-directory: ${{github.workspace}}/build
      run: cmake --install .

    - name: Create App bundle
      run: |
        # get love osx binary
        wget https://github.com/love2d/love/releases/download/11.4/love-11.4-macos.zip
        7z x love-11.4-macos.zip
        mv love.app oh3.app
        # copy files into bundle (.love folder ending to fool love into thinking there is a zip bundle to start)
        mkdir oh3.app/Contents/Resources/oh3.love
        cp -r *.lua lib assets compat extlibs game game_handler server ui input_schemes oh3.app/Contents/Resources/oh3.love
        # insert the right metadata
        patch oh3.app/Contents/Info.plist extra/osx/app-data.patch
        # work around https://github.com/actions/upload-artifact/issues/38 (executable permission not preserved) by uploading a zipped tarball
        tar -cf oh3.app.tar oh3.app

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: oh3.app.tar
        path: oh3.app.tar
