name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        sudo add-apt-repository ppa:bartbes/love-stable
        sudo apt update
        sudo apt install luajit love lua-busted
#vcpkg install ffmpeg --triplet x64-linux-dynamic
#run: sudo apt install libavformat-dev libavcodec-dev libswresample-dev libswscale-dev libavutil-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DVIDEO_EXPORT=0

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Install
      working-directory: ${{github.workspace}}/build
      run: cmake --install .

    - name: Install Pack
      run: |
        mkdir ~/.local/share/love
        mkdir ~/.local/share/love/ohtest
        mkdir ~/.local/share/love/ohtest/packs192
        wget https://tech-cmp.lambdacraft.dev:8000/VeeDefault/download192 -O VeeDefault.zip
        7z x VeeDefault.zip
        mv VeeDefault ~/.local/share/love/ohtest/packs192

    - name: Test
      working-directory: ${{github.workspace}}
      run: luajit test/main.lua
