name: Build and package for windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Install dependencies
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          git
          p7zip
          mingw-w64-x86_64-libsodium
          mingw-w64-x86_64-libluv
          mingw-w64-x86_64-sqlite3
        update: true

    - uses: actions/checkout@v3

    - name: Create App bundle
      run: |
        wget https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
        7z x love-11.5-win64.zip
        mv love-11.5-win64 oh3
        mkdir oh3/lib
        cp /mingw64/bin/libsqlite3-0.dll oh3/lib/libsqlite3.dll
        cp /mingw64/bin/libluv.dll oh3/lib/luv.dll
        cp /mingw64/bin/libwinpthread-1.dll oh3
        cp /mingw64/bin/libuv-1.dll oh3
        cp -r *.lua assets compat extlibs game game_handler server ui input_schemes oh3
        cp extra/windows/launch.bat oh3
        # create extra folder so the zip contains an oh3 folder instead of directly having all files
        mkdir zip_contents
        mv oh3 zip_contents

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: oh3
        path: zip_contents
